---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance
    image: docker.io/library/ubuntu:24.04
    pre_build_image: true
    privileged: false
    systemd: "false"
    command: sleep infinity
    rootless: true
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ${MOLECULE_PROJECT_DIRECTORY}/..
  config_options:
    defaults:
      interpreter_python: auto_silent
verifier:
  name: ansible
scenario:
  name: default
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy
